# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.IntegerField()),
                ('component', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('resolution', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('real_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='detect',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='defects.Person'),
        ),
        migrations.AddField(
            model_name='detect',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='defects.Person'),
        ),
    ]
