# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.IntegerField()),
                ('component', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('resolution', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('changed', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=30)),
                ('number_comments', models.IntegerField()),
                ('os', models.CharField(max_length=30)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='defects.Person')),
                ('depends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depends_on', to='defects.Defect')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='defects.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='detect',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='detect',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='Detect',
        ),
    ]
