# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_auto_20170507_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='blocks',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='defects.Defect'),
            preserve_default=False,
        ),
    ]
