# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_defect_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='id',
        ),
        migrations.AlterField(
            model_name='defect',
            name='bug_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
