# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0005_auto_20170507_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='blocks',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='blockers', to='defects.Defect'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='depends',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='depends_on', to='defects.Defect'),
        ),
    ]
