# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0008_auto_20170507_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='open_date',
            field=models.CharField(default='teste', max_length=30),
            preserve_default=False,
        ),
    ]
